module.exports = {
    createRaffle: ({
        id,
        channelId,
        channelName,
        additionalChannels = [],
        title,
        description,
        messageId,
        startAt,
        endTime,
        participants = [],
        winners = [],
        winnerCount,
        isFinished = false,
        memberCountStart = 0,
        ownerId,
    }) => ({
        id,
        channelId,
        channelName,
        additionalChannels,
        title,
        description,
        messageId,
        startAt,
        endTime,
        participants,
        winners,
        winnerCount,
        isFinished,
        memberCountStart,
        ownerId,
    }),
};
